# -*- coding: utf-8 -*-
"""OCR textos print.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OkPal7XJwLEAIa_FIJQyT4bqMNeE-l5l
"""

!apt-get install -y tesseract-ocr
!apt-get install -y tesseract-ocr-por
!apt-get install -y libtesseract-dev
!apt-get install -y tesseract-ocr-por

!pip install pytesseract

import cv2
import pytesseract
from PIL import Image
from io import BytesIO

# Carregue a imagem em uma variável
# Substitua 'seu_caminho_da_imagem' pelo caminho da imagem que deseja processar
image_path = input("Digite o caminho da imagem: ")
image = Image.open(image_path)

# Configure o pytesseract para utilizar o idioma português e o modo de detecção de equações matemáticas
custom_config = r'--oem 3 --psm 6 -c preserve_interword_spaces=1 -l por+equ'

# Realize o OCR na imagem
text = pytesseract.image_to_string(image, config=custom_config)

# Imprima o texto reconhecido
print(text)

